version: "3.8"
services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - app_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "gunicorn bind 0.0.0.0:8000 --workers 4 core.wsgi --reload"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    networks:
      - app_network

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "npm run dev"
    environment:
      VITE_API_URL: http://localhost:8000
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: on-failure
    networks:
      - app_network

    nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your Nginx config
      - ./frontend/dist:/usr/share/nginx/html  # React build output
      - ./backend/static:/app/static  # Django static files
      - ./backend/media:/app/media  # Django media files
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
